CREATE TABLE ERS_REIMBURSEMENT_STATUS(
    REIMB_STATUS_ID NUMBER PRIMARY KEY,
    REIMB_STATUS VARCHAR2(10)
);


CREATE TABLE ERS_REIMBURSEMENT_TYPE(
    REIMB_TYPE_ID NUMBER PRIMARY KEY,
    REIMB_TYPE VARCHAR2(10)
);

CREATE TABLE ERS_REIMBURSEMENT(
    REIMB_ID NUMBER PRIMARY KEY,
    REIMB_AMOUNT NUMBER,
    REIMB_SUBMITTED TIMESTAMP,
    REIMB_REOLVED TIMESTAMP,
    REIMB_DESCRIPTION VARCHAR2(250),
    REIMB_RECEIPT BLOB,
    REIMB_AUTHOR_FK NUMBER,
    REIMB_RESOLVER_FK NUMBER,
    REIMB_STATUS_ID_FK NUMBER,
    REIMB_TYPE_ID_FK NUMBER,  
    CONSTRAINT REIMB_STATUS_ID_FK FOREIGN KEY (REIMB_STATUS_ID_FK) REFERENCES ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID),
    CONSTRAINT REIMB_TYPE_ID_FK FOREIGN KEY (REIMB_TYPE_ID_FK) REFERENCES ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID)
);

CREATE TABLE ERS_USER_ROLES(
    ERS_USER_ROLE_ID NUMBER PRIMARY KEY,
    USER_ROLE VARCHAR2(10)
);

CREATE TABLE ERS_USERS(
    ERS_USERS_ID NUMBER,
    ERS_USERNAME VARCHAR2(50) UNIQUE,
    ERS_PASSWORD VARCHAR2(50),
    USER_FIRST_NAME VARCHAR2(100),
    USER_LAST_NAME VARCHAR2(100),
    USER_EMAIL VARCHAR2(150) UNIQUE,
    USER_ROLE_ID_FK NUMBER,
    ERS_USERS_UNv1 VARCHAR(150),
    CONSTRAINT USER_ROLE_ID_FK FOREIGN KEY (USER_ROLE_ID_FK) REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID)
);

DROP TABLE ERS_USERS;
DROP TABLE ERS_REIMBURSEMENT;

SELECT * FROM ers_reimbursement;
SELECT * FROM ers_reimbursement_status;
SELECT * FROM ers_reimbursement_type;
SELECT * FROM ers_user_roles;
SELECT * FROM ers_users;



